### ISSUE TITLE
deis-nsqd-pdb: deprecated Policy API version

### ISSUE THREAD

**Issue by blakefallow** [kingdonb/hephy-workflow-beta#3]
https://github.com/kingdonb/hephy-workflow-beta/blob/test-release/workflow/charts/nsqd/templates/nsqd-pdb.yaml
Needs to be updated to: `apiVersion: policy/v1`

**Comment by kingdonb** [comment]
Thanks for the report! I'll check it out.

We'll probably add one of these type of things in order to preserve the backwards compatibility:

https://github.com/kingdonb/hephy-workflow-beta/blob/main/controller/templates/_helpers.tmpl#L1-L12

**Comment by kingdonb** [comment]
This is closed in 2.23.12, and will be closed in 2.24.0-beta.7 when it comes out as well 🚀
